### ISSUE TITLE
想看詠唱過程~

### ISSUE THREAD

**Issue by Kuo-TingKai** [frank890417/image-optimizer#1]
可能是我法力不夠，沒辦法召喚這麼少次又這麼短時間就寫出來這樣一個app...

**Comment by frank890417** [comment]
1. write a nodejs program to convert all input files into webp
2. add multiple output (1x, 0.5x, 0.25x) of webp
3. add multiple output format: png, jpg and webp
4. make it out put width of 4096, 2048, 1024 and 512 all at the same time, and also 1x, 0.5x, 
5. make those output size a variable to control output or not, also make output of each image in sepreate folder of image name
6. the name of output file didn't show up right
7. the output file size should be 4096,2048,1024, and 1x, 0.5x, 0.25x of original width seperately
8. clear each output folder for single file if it exist, also name the scales to 1x, 0.5x, 0.25x as file name not the exact width
9. the size and scales should be seperately output
10. make size, scales and formats into a json config object

**Comment by ayugioh2003** [comment]
朝聖 
![MagicalGIF](https://user-images.githubusercontent.com/5466631/215802515-5ba972e2-80cd-460e-9efd-5199fdd480d9.gif)

**Comment by PeterCHK** [comment]
I used both code-cushman-001 and code-davinci-002, but cant reproduce the same result. 
This is the result of code-davinci-002 with temperature 0, top P 1.

/* write a nodejs program to convert all input files into webp
add multiple output (1x, 0.5x, 0.25x) of webp
add multiple output format: png, jpg and webp
make it out put width of 4096, 2048, 1024 and 512 all at the same time, and also 1x, 0.5x,
make those output size a variable to control output or not, also make output of each image in sepreate folder of image name
the name of output file didn't show up right
the output file size should be 4096,2048,1024, and 1x, 0.5x, 0.25x of original width seperately
clear each output folder for single file if it exist, also name the scales to 1x, 0.5x, 0.25x as file name not the exact width
the size and scales should be seperately output
make size, scales and formats into a json config object */

`const fs = require('fs');
const path = require('path');
const imagemin = require('imagemin');
const imageminWebp = require('imagemin-webp');
const imageminJpegtran = require('imagemin-jpegtran');
const imageminPngquant = require('imagemin-pngquant');
const imageminMozjpeg = require('imagemin-mozjpeg');
const imageminGifsicle = require('imagemin-gifsicle');
const imageminSvgo = require('imagemin-svgo');
const imageminOptipng = require('imagemin-optipng');
const imageminPngcrush = require('imagemin-pngcrush');
const imageminPngout = require('imagemin-pngout');
const imageminJpegRecompress = require('imagemin-jpeg-recompress');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminGuetzli = require('imagemin-guetzli');
const imageminZopfli = require('imagemin-zopfli');
const imageminAdvpng = require('imagemin-advpng');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');
const imageminJpegoptim = require('imagemin-jpegoptim');`

**Comment by chikiuso** [comment]
我也發現這個情況，每次一連串"詠唱"出來的給果都不同，可能要等下一個版本

**Comment by PeterCHK** [comment]
不知道能不能儲存一個成功版本時的AI再發佈呢, AI不斷更新不能確保運行結果有點不能用在production上
